### ISSUE TITLE
The "MAILCOACH_API_ENDPOINT" can't be found in the Mailcoach' API tokens screen

### ISSUE THREAD

**Issue by eddybrando** [spatie/laravel-mailcoach-sdk#11]
The README indicates

> You'll find both the API token and endpoint on Mailcoach' API tokens screen in the Mailcoach settings

when refering to the "MAILCOACH_API_TOKEN" and "MAILCOACH_API_ENDPOINT".

For Mailcoach self-hosted, there is no indication of the API endpoint in said page.

Further, I cannot get the SDK to work on localhost. I created an API token and I'm guessing the API endpoint, but whenever I call any method from the Mailcoach facade, it just keeps loading without any curl error (if I enter no API endpoint I do get a curl error).

So I guess the question is: What is the API Endpoint for a Mailcoach self-hosted Laravel application.

**Comment by freekmurze** [comment]
For self hosted the domain endpoint is the domain your hosted it on, suffixed with `/api`. We'll make this more clear in the docs. 

I'm using the SDK on my own blog without any problems. It also work locally. Have a look on how it's used in my app: https://github.com/spatie/freek.dev/blob/main/config/mailcoach-sdk.php

**Comment by eddybrando** [comment]
Thank you very much @freekmurze. Updating the documentation would be great since there are/were many sites of the self-hosted version that referenced the URL of the hosted version.

Further, I was able to fix my issue. It occurred because of single-threaded nature of PHP when running Laravel Sail locally. I just added `PHP_CLI_SERVER_WORKERS=2` to my local **.env** file to avoid hanging the server.

**Comment by plompd** [comment]
So I tried these settings:

MAILCOACH_API_ENDPOINT=https://www.careerguide.test/api (local domain)
MAILCOACH_API_TOKEN=fake-token

And this code:

```php
public static function createCampaign($record)
{
    $campaigns = Mailcoach::campaigns();
    dd($campaigns);
}
```

But I get this error:

```
The resource you are looking for could not be found.
```

What am I missing?
