### ISSUE TITLE
Does it support sending transactional email?

### ISSUE THREAD

**Issue by sammyaxe** [spatie/laravel-mailcoach-sdk#2]
I have self-hosted Mailcoach set up, and I want to enable Laravel Instance to facilitate transactional emails via self-hosted service.

**Comment by freekmurze** [comment]
Currently the SDK those not have support for the transactional mail endpoints. For now, use the API directly for that.

**Comment by ryryan** [comment]
Seems like it has since [Oct '23](https://github.com/spatie/mailcoach-sdk-php/pull/23).

**Comment by sammyaxe** [comment]
> Seems like it has since [Oct '23](https://github.com/spatie/mailcoach-sdk-php/pull/23).

I will check it out, thanks for letting me know
