### ISSUE TITLE
Mailcoach::class and testing

### ISSUE THREAD

**Issue by citricguy** [spatie/laravel-mailcoach-sdk#22]
I cannot seem to prevent HTTP requests from being made to the live API.  I've tried using the following in individual tests:

```
Http::fake([
    'https://*.mailcoach.app/*' => Http::response(['your' => 'mocked', 'data'], 200),
]);
```

I've also attempted to use `Http::preventStrayRequests();` in TestCase.php setUp(), without success. Is there some way I can prevent live API calls from being made during my tests that issue calls to Mailcoach::class (SDK)?

**Comment by edalzell** [comment]
Did you ever figure this out? If so, how?
