### ISSUE TITLE
How to fake this package?

### ISSUE THREAD

**Issue by edalzell** [spatie/laravel-mailcoach-sdk#28]
Hi there, great package!

What is the recommended way to test code that uses this package? I don't see a `fake` method anywhere and I can't use Laravel's `Http` code because this package uses Guzzle underneath, not `Client`.

Looking forward to your guidance.

**Comment by riasvdv** [comment]
I've added a `Mailcoach::fake()` method in 1.3.0 that creates a fake instance and should prevent requests from going out, you can get the requests that would have been sent with `Mailcoach::getRequests()` afterwards.

**Comment by edalzell** [comment]
You're amazing, thanks @riasvdv
